#words for hangman game

words = (
    "apple", "orange", "banana", "coconut", "pineapple", "avocado", "blueberry", "strawberry", 
    "raspberry", "blackberry", "kiwi", "grape", "watermelon", "cantaloupe", "honeydew", "peach", 
    "plum", "cherry", "mango", "papaya", "lemon", "lime", "tangerine", "grapefruit", "fig", 
    "date", "persimmon", "pomegranate", "apricot", "nectarine", "pear", "cranberry", "guava", 
    "passionfruit", "dragonfruit", "lychee", "starfruit", "elderberry", "tomato", "bellpepper", 
    "cucumber", "zucchini", "pumpkin", "squash", "broccoli", "cauliflower", "carrot", "celery", 
    "radish", "turnip", "parsnip", "lettuce", "spinach", "kale", "arugula", "chard", "bokchoy", 
    "cabbage", "brusselsprout", "asparagus", "artichoke", "mushroom", "onion", "garlic", "ginger", 
    "shallot", "leek", "scallion", "potato", "yam", "sweetpotato", "beet", "corn", "peas", 
    "greenbean", "edamame", "eggplant", "okra", "rhubarb", "chili", "jalapeno", "habanero", 
    "pepperoncini", "poblano", "serrano", "butternutsquash", "acornsquash", "spaghettisquash", 
    "avocado", "quinoa", "rice", "oats", "barley", "millet", "wheat", "cornmeal", "buckwheat", 
    "spelt", "farro", "couscous", "bulgur", "noodles", "pasta", "bread", "bagel", "croissant", 
    "muffin", "biscuit", "cracker", "tortilla", "pita", "sourdough", "ciabatta", "focaccia", 
    "brioche", "naan", "roti", "chapati", "flatbread", "englishmuffin", "toast", "wrap", "pretzel", 
    "donut", "danish", "cookie", "brownie", "cake", "cupcake", "pie", "tart", "eclair", "macaron", 
    "cheesecake", "pancake", "waffle", "syrup", "honey", "jam", "jelly", "peanutbutter", "almondbutter", 
    "cashewbutter", "hazelnutspread", "nutella", "butter", "margarine", "creamcheese", "yogurt", 
    "milk", "cream", "halfandhalf", "whippedcream", "sourcream", "buttermilk", "cheddar", "mozzarella", 
    "provolone", "swiss", "parmesan", "romano", "gouda", "havarti", "brie", "camembert", "feta", 
    "goatcheese", "bluecheese", "ricotta", "cottagecheese", "eggs", "omelet", "frittata", "quiche", 
    "scrambledeggs", "boiledeggs", "poachedeggs", "friedeggs", "bacon", "sausage", "ham", "turkey", 
    "chicken", "beef", "pork", "lamb", "veal", "duck", "goose", "fish", "salmon", "tuna", "cod", 
    "haddock", "halibut", "trout", "mackerel", "anchovy", "sardine", "shrimp", "prawn", "lobster", 
    "crab", "oyster", "mussel", "clam", "scallop", "squid", "octopus", "tofu", "tempeh", "seitan", 
    "soybean", "lentil", "chickpea", "blackbean", "kidneybean", "pintobean", "navybean", "cannellinibean", 
    "edamame", "peanut", "almond", "walnut", "pecan", "cashew", "hazelnut", "macadamia", "pistachio", 
    "brazilnut", "chestnut", "sunflowerseed", "pumpkinseed", "sesameseed", "chia", "flaxseed", 
    "hempseed", "cornchip", "potatochip", "pretzel", "popcorn", "crackers", "trailmix", "granola", 
    "cereal", "oatmeal", "smoothie", "juice", "soda", "lemonade", "icedtea", "coffe", "latte", 
    "espresso", "cappuccino", "macchiato", "mocha", "hotchocolate", "tea", "green", "black", 
    "herbal", "chai", "matcha"
)